name: Bug report
labels: [ "bug","triage" ]
description: Report a problem and help us fix it
title: Bug
body:
- type: textarea
  id: describe-the-bug
  attributes:
    label: Describe the bug
    description: A clear and concise description of what the bug is
    placeholder: A clear and concise description of what the bug is
  validations:
    required: true
- type: textarea
  id: steps-to-reproduce
  attributes:
    label: Steps to reproduce
    description: "1. do this 
                  2. do that 
                  3. now this happens"
    placeholder: "1. do this 
                  2. do that 
                  3. now this happens"
  validations:
    required: true
- type: textarea
  id: expected-behaviour
  attributes:
    label: Expected Behaviour
    description: A clear and concise description of what you expected to happen
    placeholder: A clear and concise description of what you expected to happen
  validations:
    required: true
- type: input
  id: connector-version
  attributes:
    label: Library version
    description: Which version of the connector do you use?
    placeholder: e.g. 1.0.0
  validations:
    required: true
- type: input
  id: camunda-8-version
  attributes:
    label: Camunda Platform 8 version
    description: Which version of Camunda 8 do you use?
    placeholder: e.g. 8.4.1
  validations:
    required: true
